# Generated by Django 4.0.2 on 2022-02-18 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_rename_postalcode_shippingaddress_zipcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='qty',
            new_name='quantity',
        ),
    ]
