export const EVENTS_REQUEST = 'EVENTS_REQUEST'
export const EVENTS_SUCCESS = 'EVENTS_SUCCESS'
export const EVENTS_FAIL = 'EVENTS_FAIL'

export const EVENT_DETAILS_REQUEST = 'EVENT_DETAILS_REQUEST'
export const EVENT_DETAILS_SUCCESS = 'EVENT_DETAILS_SUCCESS'
export const EVENT_DETAILS_FAIL = 'EVENT_DETAILS_FAIL'

export const RAFFLE_TICKETS_REQUEST = 'RAFFLE_TICKETS_REQUEST'
export const RAFFLE_TICKETS_SUCCESS = 'RAFFLE_TICKETS_SUCCESS'
export const RAFFLE_TICKETS_FAIL = 'RAFFLE_TICKETS_FAIL'

export const RAFFLE_TICKET_CREATE_REQUEST = 'RAFFLE_TICKET_CREATE_REQUEST'
export const RAFFLE_TICKET_CREATE_SUCCESS = 'RAFFLE_TICKET_CREATE_SUCCESS'
export const RAFFLE_TICKET_CREATE_FAIL = 'RAFFLE_TICKET_CREATE_FAIL'
export const RAFFLE_TICKET_CREATE_RESET = 'RAFFLE_TICKET_CREATE_RESET'