/* the static product data in this file is no longer used, but has been kept in the project for reference. */
/* products can be dynamically inserted into the db from the django admin dashboard. */

const products = [
  {
    '_id': '1',
    'name': 'Ralph Lauren PH2047',
    'image': '/images/Ralph Lauren PH2047.jpg',
    'description': 'Representing Ralph Lauren’s iconic heritage as a globally recognized designer, Polo Ralph Lauren celebrates a signature vision of a classic, spirited',    
    'brand': 'Ralph Lauren',
    'category': 'Glasses',
    'price': 156.00,
    'countInStock': 10,
    'rating': 4.5,
    'numReviews': 15,
  },
  {
    '_id': '2',
    'name': 'Oakley SOCKET 5.5',
    'image': '/images/Oakley SOCKET 5.5.jpg',
    'description': 'Oakley is continually solving problems with inventions in eyewear. This philosophy has made it one of the most inimitable brands, with innovations that world',
    'brand': 'Oakley',
    'category': 'Glasses',
    'price': 125.00,
    'countInStock': 10,
    'rating': 4.0,
    'numReviews': 6,
  },
  {
    '_id': '3',
    'name': 'Vogue Eyewear VO5231',
    'image': '/images/Vogue Eyewear VO5231.jpg',
    'description': 'Vogue Eyewear is for those who play with style. Fun shapes and distinctive details make its sun and optical design about what’s hot right now – but on the real',
    'brand': 'Vogue',
    'category': 'Glasses',
    'price': 139.00,
    'countInStock': 15,
    'rating': 3.5,
    'numReviews': 30,
  },
  {
    '_id': '4',
    'name': 'Michael Kors CARACAS',
    'image': '/images/Michael Kors CARACAS.jpg',
    'description': 'Michael Kors is a world-renowned, award-winning designer of luxury accessories and ready- to-wear. Michael Kors offers a glamorous, sophisticated style',    'brand': 'Michael Kors',
    'category': 'Glasses',
    'price': 73.50,
    'countInStock': 11,
    'rating': 2.5,
    'numReviews': 69,
  },
  {
    '_id': '5',
    'name': 'Armani Exchange AX1017',
    'image': '/images/Armani Exchange AX1017.jpg',
    'description': 'A|X Armani Exchange is accessible Armani, inspired by street-chic culture and meant for the young generations or for those with a young mindset. Armani',
    'brand': 'Armani Exchange',
    'category': 'Glasses',
    'price': 125.00,
    'countInStock': 17,
    'rating': 3.5,
    'numReviews': 10,
  },
  {
    '_id': '6',
    'name': 'Ray-Ban RB5169',
    'image': '/images/Ray-Ban RB5169.jpg',
    'description': 'Timeless style, authenticity and freedom of expression are the core values behind Ray-Ban glasses. The brand has been a leader in sun and prescription eyewear',    
    'brand': 'Ray-Ban',
    'category': 'Glasses',
    'price': 156.00,
    'countInStock': 10,
    'rating': 4.5,
    'numReviews': 15,
  },
]


export default products
